apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galactus-data-pvc
  namespace: galactus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galactus-logs-pvc
  namespace: galactus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
